echo "upload cfilter"
mpfshell -n -c "open COM11; put cfilter.py cfilter.py"
echo "upload constants"
mpfshell -n -c "open COM11; put constants.py constants.py"
echo "upload main"
mpfshell -n -c "open COM11; put main.py main.py"
echo "upload mpu6050"
mpfshell -n -c "open COM11; put mpu6050.py mpu6050.py"
echo "done"